environment:
    matrix:
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python36-x64"
        - PYTHON: "C:\\Python37"
        - PYTHON: "C:\\Python37-x64"
        - PYTHON: "C:\\Python38"
        - PYTHON: "C:\\Python38-x64"
        - PYTHON: "C:\\Python39"
        - PYTHON: "C:\\Python39-x64"

install:
    - "%PYTHON%\\python.exe -m pip install .[test]"

test_script:
    - "%PYTHON%\\python.exe -m flake8"
    - "%PYTHON%\\python.exe -m pytest"

build: off
deploy: off
