name: Test commit
# The name of this workflow, under which it will appear in the Actions tab.

on: [push]
# List of events that trigger this workflow.

jobs:
# List of jobs in this workflow. Jobs would usually run in parallel.
# Here we define only one job, for the entire test matrix.

    test_all:

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.6, 3.7, 3.8, 3.9]

        runs-on: ${{ matrix.os }}

        steps:
            - name: Check out code.
              uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}.
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Display Python version.
              run: python --version
            - name: Update Pip.
              run: pip install --upgrade pip
            - name: Install package and dependencies.
              run: pip install .[test]
            - name: Lint code.
              run: flake8
            - name: Run tests.
              run: pytest
